/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** API and database health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Whether first-run setup is still needed
         * @description Public. True only while no user exists.
         */
        get: operations["getSetupStatus"];
        put?: never;
        /**
         * Create the admin account and log in
         * @description Only works while no user exists; afterwards it always answers 409.
         */
        post: operations["completeSetup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in with username and password
         * @description A wrong username and a wrong password are indistinguishable.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End the session
         * @description Invalidates the session server-side. Idempotent.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The logged-in user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change your own password
         * @description Requires the current password. Ends every other session of this user.
         */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users (admin) */
        get: operations["listUsers"];
        put?: never;
        /**
         * Invite a person (admin)
         * @description Creates a pending account and a one-time invite link. The person chooses their own password.
         */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * New invite link for a pending user (admin)
         * @description Replaces any earlier link, used or not.
         */
        post: operations["reissueInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke a user's access (admin)
         * @description Ends all of their sessions. You cannot deactivate yourself.
         */
        post: operations["deactivateUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore a deactivated user (admin) */
        post: operations["activateUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invites/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Look up an invite link
         * @description Public. A used, expired or unknown token is indistinguishable.
         */
        get: operations["getInvite"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invites/{token}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set a password from an invite and log in
         * @description The token works once.
         */
        post: operations["acceptInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Your recent uploads and where each one is */
        get: operations["listUploads"];
        put?: never;
        /**
         * Start a direct-to-storage multipart upload
         * @description Returns presigned part URLs. The browser PUTs each part straight to the object store, then calls complete. The API never receives the file bytes.
         */
        post: operations["createUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One of your uploads */
        get: operations["getUpload"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** All parts are uploaded; start ingest */
        post: operations["completeUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Try ingesting a failed upload again */
        post: operations["retryUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/ingest-failures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Failed uploads from everyone (admin) */
        get: operations["listIngestFailures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tracks in the shared library
         * @description Everything unless limit and offset are given. Sorted by sort (added, newest first; title; or artist), always with a stable tie-break, so pages never overlap or skip. The total is in X-Total-Count.
         */
        get: operations["listTracks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/albums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Albums in the shared library
         * @description Everything unless limit and offset are given. Sorted by sort (added, newest first; title; or artist) with a stable tie-break. The total is in X-Total-Count.
         */
        get: operations["listAlbums"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/albums/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** An album and its tracks */
        get: operations["getAlbum"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Artists in the shared library, A to Z
         * @description Everything unless limit and offset are given. The total is in X-Total-Count.
         */
        get: operations["listArtists"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artists/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** An artist, their albums and their tracks */
        get: operations["getArtist"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tracks/{id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The audio of a track, as stored (direct play, no transcoding)
         * @description Proxied from the private object store. Supports a single byte range (start-end, open-ended, or suffix) so a player can seek. A Range header that is malformed, uses another unit or asks for several ranges is ignored and the whole file is sent.
         */
        get: operations["streamTrack"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/playback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Report a playback event
         * @description Idempotent by event id: sending the same event again answers 202 and stores nothing.
         */
        post: operations["recordPlaybackEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Your recent plays, newest first
         * @description One entry per qualifying play, so a track played twice appears twice.
         */
        get: operations["listHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history/most-played": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Your most played tracks
         * @description Counts your qualifying plays per track, highest first.
         */
        get: operations["listMostPlayed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/albums/{id}/cover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cover art for an album */
        get: operations["getAlbumCover"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateUploadRequest: {
            filename: string;
            /** Format: int64 */
            sizeBytes: number;
            /**
             * @description Defaults to All rights reserved
             * @enum {string}
             */
            license?: "All rights reserved" | "CC BY" | "CC BY-SA" | "CC BY-NC" | "CC BY-ND" | "CC BY-NC-SA" | "CC BY-NC-ND" | "CC0";
        };
        UploadPart: {
            partNumber: number;
            /** @description Presigned URL to PUT this part to */
            url: string;
        };
        UploadTicket: {
            upload: components["schemas"]["Upload"];
            /** Format: int64 */
            partSizeBytes: number;
            parts: components["schemas"]["UploadPart"][];
        };
        CompletedPart: {
            partNumber: number;
            etag: string;
        };
        CompleteUploadRequest: {
            parts: components["schemas"]["CompletedPart"][];
        };
        Upload: {
            /** Format: uuid */
            id: string;
            filename: string;
            /** Format: int64 */
            sizeBytes: number;
            /** @enum {string} */
            status: "UPLOADING" | "INGESTING" | "DONE" | "FAILED" | "DUPLICATE";
            /** @description Readable reason, present when status is FAILED */
            error?: string;
            /**
             * Format: uuid
             * @description Present when status is DONE, or DUPLICATE (the track already in the library)
             */
            trackId?: string;
            /** Format: date-time */
            createdAt: string;
        };
        IngestFailure: {
            /** Format: uuid */
            uploadId: string;
            filename: string;
            error: string;
            username: string;
            /** Format: date-time */
            failedAt: string;
        };
        Track: {
            /** Format: uuid */
            id: string;
            title: string;
            artist: string;
            /** Format: uuid */
            artistId: string;
            /** @description Username of who uploaded it */
            uploadedBy: string;
            album?: string;
            /** Format: uuid */
            albumId?: string;
            /** @description Same-origin path to the album cover, when it has one */
            coverUrl?: string;
            /** @description The album cover's dominant colour as #rrggbb, when it has a cover */
            dominantColor?: string;
            /** @enum {string} */
            license: "All rights reserved" | "CC BY" | "CC BY-SA" | "CC BY-NC" | "CC BY-ND" | "CC BY-NC-SA" | "CC BY-NC-ND" | "CC0";
            trackNumber?: number;
            year?: number;
            genre?: string;
            /** Format: int64 */
            durationMs: number;
            codec?: string;
            bitrateKbps?: number;
            /** Format: date-time */
            createdAt: string;
        };
        Album: {
            /** Format: uuid */
            id: string;
            title: string;
            artist: string;
            /** Format: uuid */
            artistId: string;
            year?: number;
            coverUrl?: string;
            /** @description The cover dominant colour as #rrggbb, when it has a cover */
            dominantColor?: string;
            trackCount: number;
            /** Format: int64 */
            durationMs: number;
        };
        AlbumDetail: {
            album: components["schemas"]["Album"];
            /** @description Who uploaded the first track */
            uploadedBy: string;
            /**
             * Format: date-time
             * @description When the first track was added
             */
            uploadedAt: string;
            tracks: components["schemas"]["Track"][];
        };
        Artist: {
            /** Format: uuid */
            id: string;
            name: string;
            albumCount: number;
            trackCount: number;
            /** @description Cover of one of their albums, when any has one */
            coverUrl?: string;
        };
        ArtistDetail: {
            artist: components["schemas"]["Artist"];
            albums: components["schemas"]["Album"][];
            /** @description All their tracks, singles included */
            tracks: components["schemas"]["Track"][];
        };
        /** @description A playback event as the player reports it. The server adds the user from the session and stores the whole envelope unchanged. play_completed is the qualifying play: sent once, at 30 seconds or half the track, whichever comes first. */
        PlaybackEventRequest: {
            /**
             * Format: uuid
             * @description Chosen by the client. Sending the same id again is harmless.
             */
            eventId: string;
            /** @description Envelope version. Currently 1. */
            schemaVersion: number;
            /** Format: uuid */
            trackId: string;
            /** @enum {string} */
            type: "play_started" | "play_completed" | "skipped";
            /**
             * Format: date-time
             * @description When it happened on the client
             */
            occurredAt: string;
            /**
             * Format: int64
             * @description Playback position in milliseconds when it happened
             */
            positionMs: number;
            /** @description Identifies the app instance, for example a per-browser random id */
            clientId: string;
        };
        Play: {
            track: components["schemas"]["Track"];
            /** Format: date-time */
            playedAt: string;
        };
        MostPlayed: {
            track: components["schemas"]["Track"];
            /** Format: int64 */
            plays: number;
        };
        UserSummary: {
            /** Format: uuid */
            id: string;
            username: string;
            /** @enum {string} */
            role: "ADMIN" | "USER";
            /** @enum {string} */
            status: "ACTIVE" | "INVITED" | "DEACTIVATED";
            /** Format: date-time */
            createdAt: string;
        };
        CreateUserRequest: {
            username: string;
            /** @enum {string} */
            role: "ADMIN" | "USER";
        };
        InviteCreated: {
            user: components["schemas"]["UserSummary"];
            /** @description Shown once. The link is /invite/{token}. */
            token: string;
            /** Format: date-time */
            expiresAt: string;
        };
        InviteInfo: {
            username: string;
        };
        AcceptInviteRequest: {
            /** Format: password */
            password: string;
        };
        ChangePasswordRequest: {
            /** Format: password */
            currentPassword: string;
            /** Format: password */
            newPassword: string;
        };
        SetupStatus: {
            setupRequired: boolean;
        };
        SetupRequest: {
            username: string;
            /** Format: password */
            password: string;
        };
        LoginRequest: {
            username: string;
            /** Format: password */
            password: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            username: string;
            /** @enum {string} */
            role: "ADMIN" | "USER";
        };
        /** @description RFC 9457 problem details */
        Problem: {
            type?: string;
            title?: string;
            status?: number;
            detail?: string;
            instance?: string;
        };
        Health: {
            /** @enum {string} */
            status: "UP" | "DOWN";
            /** @enum {string} */
            database: "UP" | "DOWN";
        };
    };
    responses: never;
    parameters: {
        /** @description Page size, 1 to 1000. Leave out (with offset) for everything. */
        PageLimit: number;
        PageOffset: number;
        /** @description How many to return (default 50, at most 200) */
        Limit: number;
        UploadId: string;
        UserId: string;
        InviteToken: string;
    };
    requestBodies: never;
    headers: {
        /** @description How many there are in all, whatever the page */
        TotalCount: number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The API is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getSetupStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Setup status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatus"];
                };
            };
        };
    };
    completeSetup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            /** @description Admin created and logged in (session cookie set) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Invalid username or password */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Setup is already complete */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Logged in (session cookie set) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Missing username or password */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Incorrect username or password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description No valid session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Wrong current password, or the new one is not acceptable */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All users, oldest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSummary"][];
                };
            };
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Pending account created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteCreated"];
                };
            };
            /** @description Invalid username or role */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Username already taken */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    reissueInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fresh invite */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteCreated"];
                };
            };
            /** @description No such user */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description The user already has a password */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    deactivateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deactivated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such user */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description You cannot deactivate yourself */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    activateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Activated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such user */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: components["parameters"]["InviteToken"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A usable invite */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteInfo"];
                };
            };
            /** @description Invalid, used or expired */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    acceptInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: components["parameters"]["InviteToken"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptInviteRequest"];
            };
        };
        responses: {
            /** @description Account active and logged in (session cookie set) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Password not acceptable */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Invalid, used or expired */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listUploads: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Upload"][];
                };
            };
        };
    };
    createUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUploadRequest"];
            };
        };
        responses: {
            /** @description Upload started */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadTicket"];
                };
            };
            /** @description Missing file name, or a file larger than 250 MB */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UploadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The upload and its ingest status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Upload"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    completeUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UploadId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteUploadRequest"];
            };
        };
        responses: {
            /** @description Ingest queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Upload"];
                };
            };
            /** @description The object store rejected the parts */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Already completed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    retryUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UploadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ingest queued again */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Upload"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Only failed uploads can be retried */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listIngestFailures: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Most recent first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestFailure"][];
                };
            };
        };
    };
    listTracks: {
        parameters: {
            query?: {
                /** @description Page size, 1 to 1000. Leave out (with offset) for everything. */
                limit?: components["parameters"]["PageLimit"];
                offset?: components["parameters"]["PageOffset"];
                sort?: "added" | "title" | "artist";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tracks */
            200: {
                headers: {
                    "X-Total-Count": components["headers"]["TotalCount"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Track"][];
                };
            };
        };
    };
    listAlbums: {
        parameters: {
            query?: {
                /** @description Page size, 1 to 1000. Leave out (with offset) for everything. */
                limit?: components["parameters"]["PageLimit"];
                offset?: components["parameters"]["PageOffset"];
                sort?: "added" | "title" | "artist";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Albums */
            200: {
                headers: {
                    "X-Total-Count": components["headers"]["TotalCount"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Album"][];
                };
            };
        };
    };
    getAlbum: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The album */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlbumDetail"];
                };
            };
            /** @description No such album */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listArtists: {
        parameters: {
            query?: {
                /** @description Page size, 1 to 1000. Leave out (with offset) for everything. */
                limit?: components["parameters"]["PageLimit"];
                offset?: components["parameters"]["PageOffset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Artists */
            200: {
                headers: {
                    "X-Total-Count": components["headers"]["TotalCount"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Artist"][];
                };
            };
        };
    };
    getArtist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The artist */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtistDetail"];
                };
            };
            /** @description No such artist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    streamTrack: {
        parameters: {
            query?: never;
            header?: {
                /** @example bytes=0-1023 */
                Range?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The whole file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/*": string;
                };
            };
            /** @description The requested byte range */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/*": string;
                };
            };
            /** @description No such track, or its file is missing from storage */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description The range starts beyond the end of the file */
            416: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    recordPlaybackEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaybackEventRequest"];
            };
        };
        responses: {
            /** @description Accepted (new or already stored) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid event */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description No such track */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description The event id is already used by another event */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listHistory: {
        parameters: {
            query?: {
                /** @description How many to return (default 50, at most 200) */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent plays */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Play"][];
                };
            };
        };
    };
    listMostPlayed: {
        parameters: {
            query?: {
                /** @description How many to return (default 50, at most 200) */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Most played */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MostPlayed"][];
                };
            };
        };
    };
    getAlbumCover: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The image */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/*": string;
                };
            };
            /** @description No such album or no cover */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
