spring:
  application:
    name: ossm-api
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/ossm}
    username: ${DATABASE_USER:ossm}
    password: ${DATABASE_PASSWORD:ossm}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

logging:
  structured:
    format:
      console: ecs

management:
  endpoints:
    web:
      exposure:
        include: health

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: false
